project_name: forego
release:
  github:
    owner: Dexus
    name: forego
  name_template: '{{.Tag}}'
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - "386"
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  - "7"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: forego
changelog:
  sort: asc
  filters:
    exclude:
    - docs
    - Merge pull request
    - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
